<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option 2_ex1-check3</name>
   <tag></tag>
   <elementGuidId>74d2b8c3-aa31-4694-bc61-73b6f587e8de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ex1-check3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ex1-check3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;Option 3 Option 4&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b1cb7e-e690-4b4d-811f-0134c6f79e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a70c608-3b09-4faa-b5c9-40cea191ab38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cb-element mr-10</value>
      <webElementGuid>3b94b6e5-d3d3-47e1-aba0-6eff92f557c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ex1-check3</value>
      <webElementGuid>7f45afce-f67c-4564-8e7f-14eae6dc87de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrapper&quot;]/section[@class=&quot;mt-30&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;smtablet:block&quot;]/div[@class=&quot;w-full px-15&quot;]/div[@class=&quot;mt-50 rounded w-full&quot;]/div[@class=&quot;input-body mt-20&quot;]/div[@class=&quot;w-full rigth-input flex items-center justify-between smtablet:block&quot;]/div[3]/input[@id=&quot;ex1-check3&quot;]</value>
      <webElementGuid>dca86259-4116-419c-bdce-325fb29089c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ex1-check3']</value>
      <webElementGuid>e2eb5805-f42a-4140-80cd-7774fead011b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>0aa2749d-7c48-4379-aa12-3a48779c7e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>84b26552-df10-4250-b1f9-18a0684f6d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ex1-check3']</value>
      <webElementGuid>66878c26-0214-456a-a27c-be842f787568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
