<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_79</name>
   <tag></tag>
   <elementGuidId>a9c4f865-18e5-4ae1-a93f-633b3fb68b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='rangeSuccess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rangeSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;79&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>7f65eef1-7860-4ce9-9913-dc1207550a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangeSuccess</value>
      <webElementGuid>846bfa85-932b-4ba4-85da-a6cd999835e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>79</value>
      <webElementGuid>5b3a1ecf-40b3-4691-9c5f-cdc69fdfcb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rangeSuccess&quot;)</value>
      <webElementGuid>8d53820c-5ad5-4cbe-9dd1-2cf9fe51dd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangeSuccess']</value>
      <webElementGuid>558ee42f-8819-4af0-815a-514e390f2014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider3']/div/output</value>
      <webElementGuid>5412f7e3-4b39-4e51-ab13-458aa277d2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/following::output[1]</value>
      <webElementGuid>53f42125-0e5f-42d6-ac87-4d122f719ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/following::output[2]</value>
      <webElementGuid>ca4440e8-3948-49a9-b8d1-93d475f6a7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/preceding::output[1]</value>
      <webElementGuid>144a4e7d-cb58-4cca-b018-e79a0fa2a533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 25'])[1]/preceding::output[2]</value>
      <webElementGuid>581e41ae-5579-46ca-82d5-126f7f9504ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='79']/parent::*</value>
      <webElementGuid>0990a4c9-07d4-4105-a623-3a375e30a5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/output</value>
      <webElementGuid>237d4450-f44a-441f-9524-ef6d967b608f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeSuccess' and (text() = '79' or . = '79')]</value>
      <webElementGuid>c3484b1a-f391-4948-9ac2-ee09cabfed07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
