<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bootstrap Dual List Demo_SearchDualList</name>
   <tag></tag>
   <elementGuidId>606d9845-de34-4c77-a60d-e06e3f252168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SearchDualList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SearchDualList&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;search&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>295a7079-1631-457e-b9f9-c76be912b6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62b59778-e715-41e6-b66f-f0074ef6ed48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchDualList</value>
      <webElementGuid>5eeea933-2a54-41f1-8867-5667706f0a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-90 pl-10 py-5 rounded</value>
      <webElementGuid>acd3de94-1499-4110-b787-23274885cef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c7d7feef-5347-4c42-a3b7-f592e63f1a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;dual-list list-left w-5/12 smtablet:w-full border border-gray-90 p-15 bg-gray-10 rounded&quot;]/div[@class=&quot;well text-right&quot;]/div[@id=&quot;listhead&quot;]/div[@class=&quot;w-10/12 smtablet:w-full&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;border border-gray-90 pl-10 py-5 rounded&quot;]</value>
      <webElementGuid>e6103fee-8eaf-4251-96ec-8e1c5ccc6506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SearchDualList']</value>
      <webElementGuid>2bcf05d5-7c30-4905-a1ed-00f9dceaed1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listhead']/div/div/input</value>
      <webElementGuid>d21f4a93-419b-437b-85a8-595d7ba001ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>646015bc-d67b-4d67-8893-6452de9f176c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SearchDualList' and @placeholder = 'search']</value>
      <webElementGuid>1046880c-5ac0-4cf9-8685-e32ae01d35b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
