<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All_SearchDualList</name>
   <tag></tag>
   <elementGuidId>def4bcbc-14f6-490d-a5a3-abb8e4b9a1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='SearchDualList'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;search&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b691b75-0ee7-44b0-9ff2-630422c0237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c653ba1-2dff-4994-bd3d-23a03b843d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchDualList</value>
      <webElementGuid>b0688064-067d-4ae2-98cf-98e415cc3efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-90 pl-10 py-5 rounded</value>
      <webElementGuid>32a5e800-b55f-4dc5-b2f0-c9bdcbb85939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ebf49101-9600-4f00-a17c-afb658e8b73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;dual-list list-right w-5/12 smtablet:w-full border border-gray-90 p-15 bg-gray-10 rounded&quot;]/div[@class=&quot;well&quot;]/div[@id=&quot;listhead&quot;]/div[@class=&quot;w-10/12 smtablet:w-full&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;border border-gray-90 pl-10 py-5 rounded&quot;]</value>
      <webElementGuid>9498d5a7-e155-4452-ba11-f89a0abb2e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='SearchDualList'])[2]</value>
      <webElementGuid>db5954e0-88fa-4851-bf9c-30cc08f9331a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listhead']/div[2]/div/input</value>
      <webElementGuid>63052a57-1229-491c-83ba-7b2636502c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8882959c-65b8-417f-9511-21e2354ea29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SearchDualList' and @placeholder = 'search']</value>
      <webElementGuid>e631e760-d9fd-46f5-ace5-38053485cbb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
