<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Danville</name>
   <tag></tag>
   <elementGuidId>48670306-66b7-4fb3-8257-e6075226b763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[3]/div/div/div/div/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Danville&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>332ce493-a23f-45a2-bf71-3892133a99bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>75af84e7-c457-4edf-bb6e-4fcdfc835662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danville</value>
      <webElementGuid>bfe88c13-06d2-4b2a-9c78-ed5f649fb6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;dual-list list-left w-5/12 smtablet:w-full border border-gray-90 p-15 bg-gray-10 rounded&quot;]/div[@class=&quot;well text-right&quot;]/ul[@class=&quot;list-group sp_list_group mb-20 mt-10&quot;]/li[@class=&quot;list-group-item&quot;]</value>
      <webElementGuid>c9224fd2-e0de-422c-8668-d6ff21ff3233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/div/div/div/ul/li[2]</value>
      <webElementGuid>0070be39-2fb2-4103-a006-5e006a937ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kedungjenar'])[1]/following::li[1]</value>
      <webElementGuid>b5eee21e-bcfe-42ba-933b-ad992e4b610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::li[2]</value>
      <webElementGuid>8703f58b-60dd-4f25-a3f9-a10b188cf370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mynamaki'])[1]/preceding::li[1]</value>
      <webElementGuid>67626f88-6fdd-4d31-9236-370234fdeb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::li[2]</value>
      <webElementGuid>d4f76e94-6735-4766-b3b7-aa5f1f15af64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Danville']/parent::*</value>
      <webElementGuid>b2a76a4e-d65e-4d32-835d-c8ec3ac2dc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div/div/div/ul/li[2]</value>
      <webElementGuid>03726ea7-ff4d-4269-8ce8-410e1861c8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Danville' or . = 'Danville')]</value>
      <webElementGuid>ca9136f0-76fa-4454-8430-5bca0bb92280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
