<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Kedungjenar_1</name>
   <tag></tag>
   <elementGuidId>e68a72e1-0b0b-4ff4-82e3-dbfaef4981ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[3]/div/div/div/div/div/div[3]/div/ul/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.list-group-item.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kedungjenar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>263e8f67-6819-4c24-a940-3a77aa8d0e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item active</value>
      <webElementGuid>57912256-27f3-4373-a5af-5eb000de859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kedungjenar</value>
      <webElementGuid>ac94d0ec-07bb-43ce-a8e7-d1a72d63c283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;dual-list list-right w-5/12 smtablet:w-full border border-gray-90 p-15 bg-gray-10 rounded&quot;]/div[@class=&quot;well&quot;]/ul[@class=&quot;list-group sp_list_group mb-20 mt-10&quot;]/li[@class=&quot;list-group-item active&quot;]</value>
      <webElementGuid>40bef424-8018-4676-a145-fca5fc2ebcf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/div/div[3]/div/ul/li[4]</value>
      <webElementGuid>3c8e277f-03ba-46a6-acb8-43aa72db75f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grange'])[1]/following::li[1]</value>
      <webElementGuid>3a4a1307-0ce1-43b9-8528-e79d072c5180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngodo'])[1]/following::li[2]</value>
      <webElementGuid>f5cb49f5-e08f-4e26-bed3-d5f400fcc770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products &amp; Features'])[1]/preceding::li[1]</value>
      <webElementGuid>c2c1d5c7-a11d-4952-bb54-646a738ae306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing Cloud'])[2]/preceding::li[1]</value>
      <webElementGuid>b3def6fa-22ea-4d4c-a790-5f5e86ea5092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kedungjenar']/parent::*</value>
      <webElementGuid>d1da85d8-1ad4-407d-9b9f-b6764ab53e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[4]</value>
      <webElementGuid>a57512fd-e650-4ced-b255-34ab3c3240dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Kedungjenar' or . = 'Kedungjenar')]</value>
      <webElementGuid>0b13b0e1-632d-45d5-a349-04340bff0fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
